language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t zhnan/ygb-apply3:0.1.0 .
  - docker push zhnan/ygb-apply3:0.1.0
